apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: proxy-stack

build:
  artifacts:
    - image: xray
      context: docker/xray/
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: proxy-stack
        chartPath: proxy-stack
        valuesFiles:
          - proxy-stack/values.yaml
